export const movieConstants = {
  GET_MOVIES_SUCCESS: 'GET_MOVIES_SUCCESS',
  GET_MOVIES_FAILURE: 'GET_MOVIES_FAILURE',

  SET_MOVIE_SUCCESS: 'SET_MOVIE_SUCCESS',
  SET_MOVIE_FAILURE: 'SET_MOVIE_FAILURE',
};
